package com.example.groviq.backEnd.dataStructures

import com.example.groviq.backEnd.searchEngine.ArtistDto
import java.util.Calendar
import java.util.concurrent.TimeUnit


data class audioSource(

    var nameOfAudioSource     : String = "",
    var artistsOfAudioSource  : List<ArtistDto> = emptyList(),
    var yearOfAudioSource     : String = "",
    var songIds: MutableList<String> = mutableListOf(),

    //params that make audiosource be saved by user
    var shouldBeSavedStrictly : Boolean = false,

    //autogenerated
    var autoGenerated   : Boolean = false,
    var timeUpdate      : Long = 0L
){
    fun shouldBeRegenerated(): Boolean {
        val cal = Calendar.getInstance().apply {
            set(Calendar.HOUR_OF_DAY, 0)
            set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
        }
        val todayMidnight = cal.timeInMillis
        return timeUpdate < todayMidnight
    }
}
