package com.example.groviq.backEnd.dataStructures

import com.example.groviq.backEnd.searchEngine.ArtistDto
import java.util.concurrent.TimeUnit


data class audioSource(

    var nameOfAudioSource     : String = "",
    var artistsOfAudioSource  : List<ArtistDto> = emptyList(),
    var yearOfAudioSource     : String = "",
    var songIds: MutableList<String> = mutableListOf(),

    //params that make audiosource be saved by user
    var shouldBeSavedStrictly : Boolean = false,

    //autogenerated
    var autoGenerated   : Boolean = false,
    var timeUpdate      : Long = 0L
){
    fun shouldBeRegenerated(ttlMillis: Long = TimeUnit.HOURS.toMillis(24)): Boolean {

        val now = System.currentTimeMillis()
        return now - timeUpdate >= ttlMillis
    }
}
